#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.stone_type.arts_and_crafts]
			gypsum = true
			white_chalk = true
			soapstone = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.eternal_starlight]
			grimstone = true
			voidstone = true
			radianite = true
			stellagmite = true
			abysslate = true
			thermabysslate = true
			cryobysslate = true
			toxite = true
			springstone = true
			nebulaite = true
			flowglaze = true

		[types.stone_type.twilightforest]
			mazestone = true
			deadrock = true

		[types.stone_type.undergarden]
			depthrock = true
			shiverstone = true
			dreadrock = true
			tremblecrust = true

		[types.stone_type.forbidden_arcanus]
			darkstone = true

		[types.mud_type.eternal_starlight]
			nightfall_mud = true

		[types.cake.creategarnished]
			pound_cake = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.wood_type.arts_and_crafts]
			cork = true

		[types.wood_type.eternal_starlight]
			lunar = true
			northland = true
			starlight_mangrove = true
			scarlet = true
			torreya = true
			jinglestem = true
			cradlewood = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.naturesaura]
			ancient = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			aurum = true
			edelwood = true

		[types.wood_type.malum]
			runewood = true
			soulwood = true

		[types.wood_type.eidolon_repraised]
			illwood = true

		[types.leaves_type.arts_and_crafts]
			cork = true

		[types.leaves_type.creategarnished]
			pine_nut = true
			hazelnut = true
			almond = true
			blossoming_almond = true
			chestnut = true

		[types.leaves_type.eternal_starlight]
			lunar = true
			northland = true
			starlight_mangrove = true
			scarlet = false
			torreya = true
			cradlewood = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.naturesaura]
			ancient = true
			golden = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.forbidden_arcanus]
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.malum]
			runewood = true
			azure_runewood = true
			soulwood = true

		[types.leaves_type.eidolon_repraised]
			illwood = true

#Disables specific entries
[entries]

		[entries.wood_type.bibliocraft]
			fancy_crafter = true
			grandfather_clock = true
			potion_shelf = true
			table = true
			bookcase = false
			tool_rack = true
			fancy_sign = true
			label = true
			fancy_clock = true
			shelf = true
			fancy_armor_stand = true

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.storagedrawers]
			trim = true
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.stone_type.stoneworks]
			tile_stairs = true
			plate_slab = true
			shingle_wall = true
			paver_stairs = true
			paver_wall = true
			shingles = true
			plate_wall = true
			plates = true
			tile_wall = true
			cracked_tiles = true
			shingle_stairs = true
			pavers = true
			tiles = true
			tile_slab = true
			plate_stairs = true
			pillar = true
			shingle_slab = true
			paver_slab = true

		[entries.stone_type.create]
			small_brick_wall = true
			cut_wall = true
			small_bricks = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			layered = true
			cut_brick_wall = true
			pillar = true
			cut_stairs = true
			cut_brick_stairs = true
			cut_brick_slab = true
			polished_cut_slab = true
			small_brick_stairs = true
			cut_bricks = true
			polished_cut_stairs = true
			polished_cut_wall = true
			cut_slab = true

		[entries.stone_type.waystones]
			waystone = true

		[entries.leaves_type.woodworks]
			leaf_pile = true
