#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Wed Jan 01 00:00:00 PST 2025
bibliocraft=true
create=true
farmersdelight=true
stoneworks=true
storagedrawers=true
twilightforest=true
