#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Wed Feb 12 07:01:21 PST 2025
farmersdelight=true
a=false
variantvanillablocks=true
stoneworks=true
create=true
quark=true
twilightforest=true
storagedrawers=true
