[crop_harvesting]
	#The blocks that should get harvested by right-clicking
	whitelist = ["minecraft:beetroots", "minecraft:carrots", "minecraft:cocoa", "minecraft:nether_wart", "minecraft:potatoes", "minecraft:wheat", "creategarnished:garlic", "creategarnished:ginger_roots", "creategarnished:peanuts", "farmersdelight:cabbages", "farmersdelight:onions", "farmersdelight:rice_panicles", "hearthandharvest:peanuts", "hexerei:sage_crop", "immersiveengineering:hemp", "primordial_harvest:paleogourd", "rusticdelight:bell_peppers", "rusticdelight:coffee", "rusticdelight:cotton", "snowyspirit:ginger", "supplementaries:flax"]
	#If the held tool should be considered when right-click harvesting
	consider_tool = true

[tree_harvesting]
	#If the tree harvester should be enabled
	enabled = false
	#The log blocks that are allowed to get harvested by the tree harvester
	#Examples: 'minecraft:oak_log', '#minecraft:logs'
	log_types = [ ]
	#The blocks that are allowed below logs that can be harvested
	#Examples: 'minecraft:dirt', '#forge:sand/colorless'
	ground_types = [ ]
	#The tools which the player is allowed to harvest trees
	allowed_tree_tools = [ ]
	#The maximum amount of logs one harvest is allowed to do
	# Default: 128
	# Range: 0 ~ 1024
	max_harvesting_count = 128

	[tree_harvesting.dynamic_breaking_speed]
		#If bigger trees should be harder to break
		enabled = true
		#The maximum amount of time a tree should take to harvest
		# Default: 10.0
		# Range: 1.0 ~ 100.0
		min_speed = 10.0
		#The amount of breaking time that gets added per harvested log
		# Default: 0.1
		# Range: 0.0 ~ 100.0
		per_log = 0.1
