
#Common Settings
[common]
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["advanced_compacting_upgrade:false", "advanced_deposit_upgrade:true", "advanced_filter_upgrade:true", "advanced_magnet_upgrade:false", "advanced_pickup_upgrade:true", "advanced_restock_upgrade:true", "advanced_void_upgrade:false", "auto_smelting_upgrade:false", "backpack:true", "compacting_upgrade:false", "crafting_upgrade:false", "deposit_upgrade:true", "diamond_backpack:true", "everlasting_upgrade:true", "feeding_upgrade:false", "filter_upgrade:true", "gold_backpack:true", "inception_upgrade:false", "iron_backpack:true", "magnet_upgrade:false", "pickup_upgrade:true", "refill_upgrade:false", "restock_upgrade:true", "smelting_upgrade:false", "upgrade_base:true", "void_upgrade:false"]

	#Leather Backpack Settings
	[common.leatherBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 18
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 1

	#Iron Backpack Settings
	[common.ironBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 27
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 1

	#Gold Backpack Settings
	[common.goldBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 36
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 2

	#Diamond Backpack Settings
	[common.diamondBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 45
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 3

	#Compacting Upgrade Settings
	[common.compactingUpgrade]
		#Number of Compacting Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Compacting Upgrade Settings
	[common.advancedCompactingUpgrade]
		#Number of Advanced Compacting Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Deposit Upgrade Settings
	[common.depositUpgrade]
		#Number of Deposit Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 8
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Advanced Deposit Upgrade Settings
	[common.advancedDepositUpgrade]
		#Number of Advanced Deposit Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Feeding Upgrade Settings
	[common.feedingUpgrade]
		#Number of Feeding Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Filter Upgrade Settings
	[common.filterUpgrade]
		#Number of Filter Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 8
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Advanced Filter Upgrade Settings
	[common.advancedFilterUpgrade]
		#Number of Advanced Filter Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Magnet Upgrade Settings
	[common.magnetUpgrade]
		#Number of Magnet Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3
		#Range around backpack in blocks at which magnet will pickup items
		#Range: 1 ~ 20
		magnetRange = 3

	#Advanced Magnet Upgrade Settings
	[common.advancedMagnetUpgrade]
		#Number of Advanced Magnet Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4
		#Range around backpack in blocks at which magnet will pickup items
		#Range: 1 ~ 20
		magnetRange = 5

	#Pickup Upgrade Settings
	[common.pickupUpgrade]
		#Number of Pickup Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 8
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Advanced Pickup Upgrade Settings
	[common.advancedPickupUpgrade]
		#Number of Advanced Pickup Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Refill Upgrade Settings
	[common.refillUpgrade]
		#Number of Refill Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 6
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Restock Upgrade Settings
	[common.restockUpgrade]
		#Number of Restock Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 8
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Advanced Restock Upgrade Settings
	[common.advancedRestockUpgrade]
		#Number of Advanced Restock Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Void Upgrade Settings
	[common.voidUpgrade]
		#Number of Void Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Void Upgrade Settings
	[common.advancedVoidUpgrade]
		#Number of Advanced Void Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Smelting Upgrade Settings
	[common.smeltingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0

	#Auto-Smelting Upgrade Settings
	[common.autoSmeltingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0
		#Number of input filter slots
		#Range: 1 ~ 20
		inputFilterSlots = 8
		#Number of input filter slots displayed in a row
		#Range: 1 ~ 6
		inputFilterSlotsInRow = 4
		#Number of fuel filter slots
		#Range: 1 ~ 20
		fuelFilterSlots = 4
		#Number of fuel filter slots displayed in a row
		#Range: 1 ~ 6
		fuelFilterSlotsInRow = 4

	#Inception Upgrade Settings
	[common.inceptionUpgrade]
		#Allows / Disallows backpack upgrades to work with inventories of Backpacks in the Backpack with Inception Upgrade
		upgradesUseInventoriesOfBackpacksInBackpack = true
		#Allows / Disallows upgrades to be functional even when they are in Backpacks in the inventory of Backpack with Inception Upgrade
		upgradesInContainedBackpacksAreFunctional = true

